### ISSUE TITLE
issue with transition to kubernetes/op-scim-config.yaml 

### ISSUE THREAD

**Issue by sir-wally** [1Password/scim-examples#119] opened 2020-10-20 19:39 UTC
Had a deployment work fine last week to azure kube service before the latest commit. Tried to same deployment today to AKS with the updated code and nothing seems to work. Not listening on 443/80, cert didn't get created etc.. 

I think there's an issue with the vars in the new config.yaml that's being used. Looking into it today will update what I find.

**Comment by alicethorne-ab** [comment] 2020-10-21 17:07
Thank you for reaching out. If you have an example of any log files or error messages that you're experiencing, that would be a great help in resolving what you're experiencing.

Moving to ConfigMap/environment variables format was intended to make configuration of the SCIM Bridge more straight-forward than passing in raw arguments to the `op-scim` binary, so it'd be a great help in making sure it's rock solid.

**Comment by sir-wally** [comment] 2020-10-22 17:55
Hi thanks for the response. I haven't gotten it working yet. Here's what I think are the relevant logs from the kubevents log. The serviceaccount "tunnelfront" not found error makes me wonder if there's an issue with auth config.  

There are the auth settings I'm using, I'll try tinkering with those.

![image](https://user-images.githubusercontent.com/37912176/96910821-e105e380-1454-11eb-9348-dfc15318b176.png)


`10/22/2020, 10:30:23.000 AM	kube-system	aks-agentpool-13325411-0	Pod	coredns-869cb84759-ltvvr	Unhealthy	Readiness probe failed: Get http://10.244.0.6:8181/ready: dial tcp 10.244.0.6:8181: connect: connection refused	Warning	kubelet	
10:30:23.000 AM	kube-system	aks-agentpool-13325411-0	ReplicaSet	tunnelfront-7599b485f6	FailedCreate	Error creating: pods "tunnelfront-7599b485f6-" is forbidden: error looking up service account kube-system/tunnelfront: serviceaccount "tunnelfront" not found	Warning	replicaset-controller	
10/22/2020, 10:34:23.000 AM	default	aks-agentpool-13325411-0	Pod	op-scim-bridge-866f7bb859-7bnfj	Unhealthy	Liveness probe failed: Get https://10.244.0.12:443/ping: dial tcp 10.244.0.12:443: connect: connection refused	Warning	kubelet	10/22/2020, 10:33:59.000 AM	9	scim	KubeEvents	Containers
`

Also I think maybe https://support.1password.com/scim-deploy-azure/ needs to be updated with the new instructions you wrote up here as the differ a bit (references to op-scim-config.yaml) https://github.com/1Password/scim-examples/tree/master/kubernetes

**Comment by sir-wally** [comment] 2020-10-22 19:13
I'm not sure what the issue is but I have it working in AKS using and older build https://github.com/1Password/scim-examples/tree/59d17fe84fc0bc07012bec1b0c1304010f3cd63e/kubernetes

**Comment by platima** [comment] 2020-10-23 07:36
Yeah confirmed, so 1) the doco says to add the args line, however, that is now in op-scim-config.yaml that needs to be applied too (doco update please?), however, even then the 1.6.0 image keeps crash looping.

I grabbed the yaml files for 1.4.4 and it worked fine first go.

**Closed** 2020-10-24 14:57 UTC
Labels: bug

**Comment by alicethorne-ab** [comment] 2020-10-26 16:15
Hello all. I pushed a new version of the `scim-examples` repo.

For now, you'll need to follow the README in this repo. I'll be working on updating the official documentation shortly.
